apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-preload-vm
spec:
  selector:
    matchLabels:
      app: image-preload-vm
  template:
    metadata:
      labels:
        app: image-preload-vm
    spec:
      containers:
      - name: preload
        image: quay.io/ellorent/fedora-with-test-tooling:tcpdump
      tolerations:
      - operator: Exists
      nodeSelector:
        node-role.kubernetes.io/worker: ""
