apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-preload
spec:
  selector:
    matchLabels:
      app: image-preload
  template:
    metadata:
      labels:
        app: image-preload
    spec:
      # Add an initContainer to preload additional images
      initContainers:
      - name: preload-iperf3
        image: networkstatic/iperf3
        command: ["true"]

      containers:
      - name: preload
        image: quay.io/dougbtv/alpine
        command: ["sh", "-c", "sleep 3600"]

      tolerations:
      - operator: Exists
      nodeSelector:
        node-role.kubernetes.io/worker: ""
