apiVersion: v1
kind: Pod
metadata:
  name: pingpod
spec:
  containers:
  - name: pingpod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: quay.io/dougbtv/alpine
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
