apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: network-c
spec:
  topology: Layer2 
  layer2: 
    ipamLifecycle: Persistent
    role: Primary 
    subnets:
      - "10.0.0.0/24"
