---
apiVersion: k8s.cni.cncf.io/v1                                                  
kind: NetworkAttachmentDefinition                                               
metadata:                                                                       
  namespace: namespace-c
  name: l2
spec:                                                                           
  config: |2                                                                    
    {                                                                           
            "cniVersion": "0.3.0",                                              
            "name": "l2-network",                                               
            "type": "ovn-k8s-cni-overlay",                                      
            "topology":"layer2",                                                
            "subnets": "10.100.200.0/24,2014:100:200::0/60",                                       
            "netAttachDefName": "namespace-c/l2",                               
            "allowPersistentIPs": true,
            "role": "primary"
    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: namespace-c
  name: fedora-vm-a-iperf3
spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  selector:
    vm.kubevirt.io/name: fedora-vm-a
  ports:
    - protocol: TCP
      port: 5201
---
apiVersion: v1
kind: Service
metadata:
  namespace: namespace-c
  name: fedora-vm-b-iperf3
spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  selector:
    vm.kubevirt.io/name: fedora-vm-b
  ports:
    - protocol: TCP
      port: 5201
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    special: fedora-vm-a
  namespace: namespace-c
  name: fedora-vm-a
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: ovn-kubernetes
            binding:
              name: defaultPodNetworkBinding
          rng: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: ovn-kubernetes
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/ellorent/fedora-with-test-tooling:tcpdump
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
          networkData: |-
            version: 2
            ethernets:
              eth0:
                dhcp4: true
                dhcp6: true
                ipv6-address-generation: eui64
        name: cloudinitdisk
# ---
# apiVersion: kubevirt.io/v1
# kind: VirtualMachine
# metadata:
#   labels:
#     special: fedora-vm-b
#   namespace: namespace-c
#   name: fedora-vm-b
# spec:
#   running: true
#   template:
#     spec:
#       domain:
#         devices:
#           disks:
#           - disk:
#               bus: virtio
#             name: containerdisk
#           - disk:
#               bus: virtio
#             name: cloudinitdisk
#           interfaces:
#           - name: pod
#             binding:
#               name: defaultPodNetworkBinding
#           rng: {}
#         resources:
#           requests:
#             memory: 1024M
#       networks:
#       - name: pod
#         pod: {}
#       terminationGracePeriodSeconds: 0
#       volumes:
#       - containerDisk:
#           image: quay.io/ellorent/fedora-with-test-tooling:tcpdump
#         name: containerdisk
#       - cloudInitNoCloud:
#           userData: |-
#             #cloud-config
#             password: fedora
#             chpasswd: { expire: False }
#           networkData: |-
#             version: 2
#             ethernets:
#               eth0:
#                 dhcp4: true
#                 dhcp6: true
#                 ipv6-address-generation: eui64
#         name: cloudinitdisk